apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pokemons.datacenter.com
spec:
  group: datacenter.com
  names:
    kind: Pokemon
    plural: pokemons
    singular: pokemon
    shortNames:
      - pkm        
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            name:
              type: string
